export const RESET_STATE = "RESET_STATE";
export const SET_REPORT_PARAMETERS = "SET_REPORT_PARAMETERS";
export const SET_DATASETS = "SET_DATASETS";
export const SET_LOADING = "SET_LOADING";

export const SIDE_BAR_OPEN_HANDLER = "SIDE_BAR_OPEN_HANDLER";
export const IS_SAVED_NEW_DATASET_SETTINGS = "IS_SAVED_SIDE_BAR_SETTINGS";
export const IS_SAVED_NEW_PARAMETERS_SETTINGS =
  "IS_SAVED_NEW_PARAMETERS_SETTINGS";

export const SET_NEW_DATASET_STATE = "SET_NEW_DATASET_STATE";
export const SET_NEW_PARAMETERS_STATE = "SET_NEW_PARAMETERS_STATE";

export const SET_SETTINGS_STATE = "SET_SETTINGS_STATE";

export const SET_WIDGETS_LIST = "SET_WIDGETS_LIST";

export const SHOW_ALERT = "SHOW_ALERT";
